import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { Medicine, RefillSuggestion } from '../types.ts';

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

export interface ReportData {
  medicines: Medicine[];
  refillSuggestions: RefillSuggestion[];
  userEmail: string;
  userName: string;
}

export const reportService = {
  generateInventoryReport: (data: ReportData) => {
    const expiredCount = data.medicines.filter(m => {
      const expDate = new Date(m.expiryDate?.seconds * 1000 || m.expiryDate);
      return expDate < new Date();
    }).length;

    const lowStock = data.medicines.filter(m => m.quantity < 5).length;

    return {
      timestamp: new Date().toISOString(),
      summary: {
        totalItems: data.medicines.length,
        expiredCount,
        lowStockCount: lowStock,
        totalValue: data.medicines.reduce((sum, m) => sum + (m.estimatedValue || 0), 0)
      },
      inventory: data.medicines.map(m => ({
        Name: m.name,
        Quantity: `${m.quantity} ${m.unit}`,
        Expiry: new Date(m.expiryDate?.seconds * 1000 || m.expiryDate).toLocaleDateString(),
        Status: m.status
      })),
      refills: data.refillSuggestions.map(r => ({
        Medicine: r.name,
        Urgency: r.urgency,
        Reason: r.reason
      }))
    };
  },

  exportToPDF: (data: ReportData) => {
    const doc = new jsPDF() as any;
    const report = reportService.generateInventoryReport(data);

    // Header
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text('SafeShelf AI: Inventory Report', 15, 25);
    
    doc.setFontSize(10);
    doc.text(`Generated for: ${data.userName} (${data.userEmail})`, 15, 33);
    doc.text(`Date: ${new Date().toLocaleString()}`, 160, 33);

    // Summary Section
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.text('Inventory Summary', 15, 55);
    
    const summaryData = [
      ['Total Items', report.summary.totalItems.toString()],
      ['Expired Items', report.summary.expiredCount.toString()],
      ['Low Stock Items', report.summary.lowStockCount.toString()],
      ['Total Estimated Value', `$${report.summary.totalValue.toFixed(2)}`]
    ];

    doc.autoTable({
      startY: 60,
      head: [['Metric', 'Value']],
      body: summaryData,
      theme: 'striped',
      headStyles: { fillColor: [79, 70, 229] } // indigo-600
    });

    // Inventory Table
    doc.text('Full Inventory Status', 15, doc.lastAutoTable.finalY + 15);
    
    doc.autoTable({
      startY: doc.lastAutoTable.finalY + 20,
      head: [['Medicine Name', 'Quantity', 'Expiry Date', 'Status']],
      body: report.inventory.map(i => [i.Name, i.Quantity, i.Expiry, i.Status]),
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42] }
    });

    // Refill Suggestions
    if (report.refills.length > 0) {
      doc.text('Recommended Refills (Quantis Engine)', 15, doc.lastAutoTable.finalY + 15);
      doc.autoTable({
        startY: doc.lastAutoTable.finalY + 20,
        head: [['Medicine', 'Urgency', 'Reason']],
        body: report.refills.map(r => [r.Medicine, r.Urgency.toUpperCase(), r.Reason]),
        theme: 'striped',
        headStyles: { fillColor: [16, 185, 129] } // emerald-500
      });
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by SafeShelf AI Assistant. This report is for information purposes only.', 15, doc.internal.pageSize.height - 10);

    doc.save(`SafeShelf_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  },

  exportToExcel: (data: ReportData) => {
    const report = reportService.generateInventoryReport(data);
    
    const wb = XLSX.utils.book_new();
    
    // Summary Sheet
    const wsSummary = XLSX.utils.json_to_sheet([
      { Metric: 'Total Items', Value: report.summary.totalItems },
      { Metric: 'Expired Items', Value: report.summary.expiredCount },
      { Metric: 'Low Stock Items', Value: report.summary.lowStockCount },
      { Metric: 'Total Value ($)', Value: report.summary.totalValue }
    ]);
    XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');
    
    // Inventory Sheet
    const wsInventory = XLSX.utils.json_to_sheet(report.inventory);
    XLSX.utils.book_append_sheet(wb, wsInventory, 'Inventory');
    
    // Refills Sheet
    const wsRefills = XLSX.utils.json_to_sheet(report.refills);
    XLSX.utils.book_append_sheet(wb, wsRefills, 'Refill Suggestions');
    
    XLSX.writeFile(wb, `SafeShelf_Report_${new Date().toISOString().split('T')[0]}.xlsx`);
  },

  shareOnWhatsApp: (data: ReportData) => {
    const report = reportService.generateInventoryReport(data);
    const message = `*SafeShelf AI Inventory Report*\n\n` +
      `Summary:\n` +
      `- Total Items: ${report.summary.totalItems}\n` +
      `- Expired: ${report.summary.expiredCount}\n` +
      `- Low Stock: ${report.summary.lowStockCount}\n` +
      `- Total Value: $${report.summary.totalValue.toFixed(2)}\n\n` +
      `_Critical Refills:_\n` +
      report.refills.map(r => `• ${r.Medicine} (${r.Urgency})`).join('\n') +
      `\n\nGenerated via SafeShelf AI Assistant`;

    const encodedMessage = encodeURIComponent(message);
    window.open(`https://wa.me/?text=${encodedMessage}`, '_blank');
  },

  shareViaEmail: (data: ReportData) => {
    const report = reportService.generateInventoryReport(data);
    const body = `SafeShelf AI Inventory Report\n\n` +
      `Total Items: ${report.summary.totalItems}\n` +
      `Expired Items: ${report.summary.expiredCount}\n` +
      `Low Stock: ${report.summary.lowStockCount}\n` +
      `Total Value: $${report.summary.totalValue.toFixed(2)}\n\n` +
      `Detailed inventory and refills suggestions attached in PDF/Excel (Please download from dashboard).`;

    const mailto = `mailto:?subject=SafeShelf AI Inventory Report&body=${encodeURIComponent(body)}`;
    window.location.href = mailto;
  }
};
